// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Test1665845241938231900 is the golang structure of table test_1665845241938231900 for DAO operations like Where/Data.
type Test1665845241938231900 struct {
	g.Meta     `orm:"table:test_1665845241938231900, do:true"`
	Id         interface{} //
	Passport   interface{} //
	Password   interface{} //
	Nickname   interface{} //
	CreateTime *gtime.Time //
}
