// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// Test1665845241938231900Dao is the data access object for table test_1665845241938231900.
type Test1665845241938231900Dao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns Test1665845241938231900Columns // columns contains all the column names of Table for convenient usage.
}

// Test1665845241938231900Columns defines and stores column names for table test_1665845241938231900.
type Test1665845241938231900Columns struct {
	Id         string //
	Passport   string //
	Password   string //
	Nickname   string //
	CreateTime string //
}

// test1665845241938231900Columns holds the columns for table test_1665845241938231900.
var test1665845241938231900Columns = Test1665845241938231900Columns{
	Id:         "id",
	Passport:   "passport",
	Password:   "password",
	Nickname:   "nickname",
	CreateTime: "create_time",
}

// NewTest1665845241938231900Dao creates and returns a new DAO object for table data access.
func NewTest1665845241938231900Dao() *Test1665845241938231900Dao {
	return &Test1665845241938231900Dao{
		group:   "default",
		table:   "test_1665845241938231900",
		columns: test1665845241938231900Columns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *Test1665845241938231900Dao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *Test1665845241938231900Dao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *Test1665845241938231900Dao) Columns() Test1665845241938231900Columns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *Test1665845241938231900Dao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *Test1665845241938231900Dao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *Test1665845241938231900Dao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
