// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Test1665845241938231900 is the golang structure for table test_1665845241938231900.
type Test1665845241938231900 struct {
	Id         uint        `json:"id"         ` //
	Passport   string      `json:"passport"   ` //
	Password   string      `json:"password"   ` //
	Nickname   string      `json:"nickname"   ` //
	CreateTime *gtime.Time `json:"createTime" ` //
}
